apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xgqf4ba8q-dotnet-basic-gitops-repository
spec:
  url: https://github.com/tnevrlka-rhtap/xgqf4ba8q-dotnet-basic-gitops