apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xgqf4ba8q-dotnet-basic
  janus-idp.io/tekton: xgqf4ba8q-dotnet-basic
  backstage.io/kubernetes-id: xgqf4ba8q-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xgqf4ba8q-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
